app:
  name: "Kultur API"
  description: "Rest API for Kultur website"
server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/Kultur
    #username: postgres
    #password: admin
    url: jdbc:postgresql://${CC_HOST}:${CC_PORT}/${CC_DB}
    username: ${CC_USER}
    password: ${CC_PW}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui:
  path: /api/docs
  operationsSorter: method
